"""
Bug Bounty Report Generator.

Features:
- Auto-generate bug bounty reports
- Multiple templates (HackerOne, Bugcrowd, etc.)
- Markdown and PDF output
- Include evidence/screenshots
- CVSS score calculation
- Remediation suggestions
"""

from typing import List, Dict, Optional, Any
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate professional bug bounty reports."""
    
    def __init__(self):
        """Initialize report generator."""
        self.templates = {
            'hackerone': self._hackerone_template,
            'bugcrowd': self._bugcrowd_template,
            'generic': self._generic_template
        }
        
        # CVSS v3.1 scoring metrics
        self.cvss_metrics = {
            'attack_vector': {
                'network': 0.85,
                'adjacent': 0.62,
                'local': 0.55,
                'physical': 0.2
            },
            'attack_complexity': {
                'low': 0.77,
                'high': 0.44
            },
            'privileges_required': {
                'none': 0.85,
                'low': 0.62,
                'high': 0.27
            },
            'user_interaction': {
                'none': 0.85,
                'required': 0.62
            },
            'impact': {
                'high': 0.56,
                'low': 0.22,
                'none': 0
            }
        }
    
    def generate_report(self,
                       vulnerability: Dict[str, Any],
                       template: str = 'generic',
                       output_format: str = 'markdown') -> str:
        """
        Generate a bug bounty report.
        
        Args:
            vulnerability: Vulnerability details
            template: Template to use ('hackerone', 'bugcrowd', 'generic')
            output_format: Output format ('markdown', 'html')
            
        Returns:
            Generated report as string
        """
        if template not in self.templates:
            logger.warning(f"Unknown template {template}, using generic")
            template = 'generic'
        
        # Generate report using template
        report = self.templates[template](vulnerability)
        
        if output_format == 'html':
            report = self._markdown_to_html(report)
        
        return report
    
    def _generic_template(self, vuln: Dict[str, Any]) -> str:
        """Generate generic bug bounty report."""
        title = vuln.get('title', 'Security Vulnerability Report')
        severity = vuln.get('severity', 'Unknown')
        asset = vuln.get('asset', 'Unknown')
        description = vuln.get('description', '')
        impact = vuln.get('impact', '')
        steps = vuln.get('steps_to_reproduce', [])
        poc = vuln.get('poc', '')
        remediation = vuln.get('remediation', '')
        cvss = vuln.get('cvss_score', 'N/A')
        
        report_lines = [
            f"# {title}",
            "",
            "## Summary",
            f"**Severity:** {severity}",
            f"**Asset:** {asset}",
            f"**CVSS Score:** {cvss}",
            f"**Date:** {datetime.now().strftime('%Y-%m-%d')}",
            "",
            "## Description",
            description,
            "",
            "## Impact",
            impact,
            "",
            "## Steps to Reproduce",
        ]
        
        if steps:
            for i, step in enumerate(steps, 1):
                report_lines.append(f"{i}. {step}")
        else:
            report_lines.append("_No steps provided_")
        
        report_lines.extend([
            "",
            "## Proof of Concept",
            "```",
            poc if poc else "_No PoC provided_",
            "```",
            "",
            "## Remediation",
            remediation if remediation else "_No remediation provided_",
            "",
            "---",
            f"Report generated by xnLinkFinder-Z on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        ])
        
        return "\n".join(report_lines)
    
    def _hackerone_template(self, vuln: Dict[str, Any]) -> str:
        """Generate HackerOne-style report."""
        report_lines = [
            f"# {vuln.get('title', 'Vulnerability Report')}",
            "",
            "## Summary",
            vuln.get('description', ''),
            "",
            "## Steps To Reproduce",
        ]
        
        steps = vuln.get('steps_to_reproduce', [])
        if steps:
            for i, step in enumerate(steps, 1):
                report_lines.append(f"{i}. {step}")
        
        report_lines.extend([
            "",
            "## Impact",
            vuln.get('impact', ''),
            "",
            "## Supporting Material/References",
        ])
        
        references = vuln.get('references', [])
        if references:
            for ref in references:
                report_lines.append(f"- {ref}")
        else:
            report_lines.append("_No references_")
        
        report_lines.extend([
            "",
            "## Suggested Fix",
            vuln.get('remediation', '_No suggestion provided_'),
        ])
        
        return "\n".join(report_lines)
    
    def _bugcrowd_template(self, vuln: Dict[str, Any]) -> str:
        """Generate Bugcrowd-style report."""
        severity_map = {
            'critical': 'P1',
            'high': 'P2',
            'medium': 'P3',
            'low': 'P4'
        }
        
        severity = vuln.get('severity', 'medium').lower()
        priority = severity_map.get(severity, 'P3')
        
        report_lines = [
            f"# {vuln.get('title', 'Security Finding')}",
            "",
            f"**Priority:** {priority}",
            f"**Category:** {vuln.get('category', 'Other')}",
            f"**URL:** {vuln.get('asset', 'N/A')}",
            "",
            "## Description",
            vuln.get('description', ''),
            "",
            "## Proof of Concept",
            vuln.get('poc', ''),
            "",
            "## Impact",
            vuln.get('impact', ''),
            "",
            "## Remediation Recommendation",
            vuln.get('remediation', ''),
        ]
        
        return "\n".join(report_lines)
    
    def calculate_cvss_score(self, metrics: Dict[str, str]) -> Dict[str, Any]:
        """
        Calculate CVSS v3.1 score.
        
        Args:
            metrics: CVSS metrics dictionary
            
        Returns:
            Dictionary with score and severity
        """
        try:
            # Base score calculation (simplified)
            av = self.cvss_metrics['attack_vector'].get(metrics.get('attack_vector', 'network'), 0.85)
            ac = self.cvss_metrics['attack_complexity'].get(metrics.get('attack_complexity', 'low'), 0.77)
            pr = self.cvss_metrics['privileges_required'].get(metrics.get('privileges_required', 'none'), 0.85)
            ui = self.cvss_metrics['user_interaction'].get(metrics.get('user_interaction', 'none'), 0.85)
            
            conf_impact = self.cvss_metrics['impact'].get(metrics.get('confidentiality', 'high'), 0.56)
            int_impact = self.cvss_metrics['impact'].get(metrics.get('integrity', 'high'), 0.56)
            avail_impact = self.cvss_metrics['impact'].get(metrics.get('availability', 'high'), 0.56)
            
            # Simplified calculation
            exploitability = 8.22 * av * ac * pr * ui
            impact = 1 - ((1 - conf_impact) * (1 - int_impact) * (1 - avail_impact))
            
            if impact <= 0:
                base_score = 0
            else:
                base_score = min(10.0, exploitability + impact * 6.42)
            
            base_score = round(base_score, 1)
            
            # Determine severity
            if base_score >= 9.0:
                severity = 'Critical'
            elif base_score >= 7.0:
                severity = 'High'
            elif base_score >= 4.0:
                severity = 'Medium'
            elif base_score > 0:
                severity = 'Low'
            else:
                severity = 'None'
            
            return {
                'score': base_score,
                'severity': severity,
                'vector': self._generate_cvss_vector(metrics)
            }
        
        except Exception as e:
            logger.error(f"Error calculating CVSS score: {e}")
            return {
                'score': 0.0,
                'severity': 'Unknown',
                'vector': 'N/A'
            }
    
    def _generate_cvss_vector(self, metrics: Dict[str, str]) -> str:
        """Generate CVSS vector string."""
        vector_parts = ['CVSS:3.1']
        
        metric_codes = {
            'attack_vector': 'AV',
            'attack_complexity': 'AC',
            'privileges_required': 'PR',
            'user_interaction': 'UI',
            'scope': 'S',
            'confidentiality': 'C',
            'integrity': 'I',
            'availability': 'A'
        }
        
        value_codes = {
            'network': 'N',
            'adjacent': 'A',
            'local': 'L',
            'physical': 'P',
            'low': 'L',
            'high': 'H',
            'none': 'N',
            'required': 'R',
            'unchanged': 'U',
            'changed': 'C'
        }
        
        for metric, code in metric_codes.items():
            if metric in metrics:
                value = metrics[metric].lower()
                value_code = value_codes.get(value, value[0].upper())
                vector_parts.append(f"{code}:{value_code}")
        
        return '/'.join(vector_parts)
    
    def suggest_remediation(self, vulnerability_type: str) -> str:
        """
        Suggest remediation based on vulnerability type.
        
        Args:
            vulnerability_type: Type of vulnerability
            
        Returns:
            Remediation suggestion
        """
        remediations = {
            'xss': (
                "1. Implement proper input validation and sanitization\n"
                "2. Use Content Security Policy (CSP) headers\n"
                "3. Encode output based on context (HTML, JavaScript, URL)\n"
                "4. Use templating engines with auto-escaping enabled"
            ),
            'sqli': (
                "1. Use parameterized queries (prepared statements)\n"
                "2. Implement proper input validation\n"
                "3. Use ORM frameworks where possible\n"
                "4. Apply principle of least privilege for database accounts\n"
                "5. Implement web application firewall (WAF) rules"
            ),
            'csrf': (
                "1. Implement anti-CSRF tokens for state-changing operations\n"
                "2. Validate the Origin and Referer headers\n"
                "3. Use SameSite cookie attribute\n"
                "4. Require re-authentication for sensitive operations"
            ),
            'idor': (
                "1. Implement proper authorization checks\n"
                "2. Use indirect object references (mapping)\n"
                "3. Validate user permissions for each request\n"
                "4. Implement access control lists (ACLs)"
            ),
            'ssrf': (
                "1. Implement whitelist-based URL validation\n"
                "2. Disable or restrict URL redirects\n"
                "3. Use network segmentation\n"
                "4. Validate and sanitize all user-supplied URLs"
            ),
        }
        
        vuln_type_lower = vulnerability_type.lower()
        for key, remediation in remediations.items():
            if key in vuln_type_lower:
                return remediation
        
        return "Implement proper security controls and follow OWASP guidelines."
    
    def _markdown_to_html(self, markdown: str) -> str:
        """Convert markdown to HTML (simplified)."""
        html = markdown
        
        # Headers
        html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        
        # Bold
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
        
        # Code blocks
        html = re.sub(r'```(.+?)```', r'<pre><code>\1</code></pre>', html, flags=re.DOTALL)
        
        # Lists
        html = re.sub(r'^\d+\. (.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
        html = re.sub(r'^- (.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
        
        # Wrap in HTML structure
        html = f"<html><body>{html}</body></html>"
        
        return html


def generate_report(vulnerability: Dict[str, Any], template: str = 'generic') -> str:
    """
    Convenience function to generate a report.
    
    Args:
        vulnerability: Vulnerability details
        template: Template name
        
    Returns:
        Generated report
    """
    generator = ReportGenerator()
    return generator.generate_report(vulnerability, template=template)
