replicaCount: 3

image:
  repository: xnlinkfinder/xnlinkfinder-z
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

redis:
  enabled: true
  host: redis-master
  port: 6379

rabbitmq:
  enabled: false
  host: rabbitmq
  port: 5672
